name: Reusable Node App CI

on:
  workflow_call:
    inputs:
      release-channel:
        description: 'Which channel is being built (develop or main)'
        required: true
        type: string
      run_build:
        description: 'Whether to run production build'
        required: false
        default: false
        type: boolean
      node_version:
        description: 'Node version to use'
        required: false
        default: '20'
        type: string

permissions:
  contents: read

jobs:
  quality-checks:
    name: Quality checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: npm ci

      - name: Run quality checks
        run: ./scripts/node/node-quality.sh
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: quality-checks
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: .wendara-ci-actions/scripts/node/run-node-unit-tests.sh

  build:
    name: Production build
    if: ${{ inputs.run_build }}
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: npm ci

      - name: Run production build
        run: .wendara-ci-actions/scripts/node/build-node-app.sh
